import type { Metadata } from "next";
import "./globals.css";
import TopLevel from "./components/TopLevel";
import NavBar from "./components/NavBar";
import Footer from "./components/Footer";



export const metadata: Metadata = {
  title: "TopShop - online marketplace",
  description: "Generated by Syed Shahmir Sultan",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="overflow-hidden">
        <TopLevel/>
        <NavBar/>
        {children}
        <Footer/></body>
    </html>
  );
}
